---
name: stripe
synopsis: Client for the Stripe payment API
version: 1.0.0.0

license: MIT

dependencies:
  - aeson
  - aeson-casing
  - base
  - case-insensitive
  - crypto-api
  - cryptonite
  - email-validate
  - generic-lens
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-text
  - genvalidity-time
  - http-api-data
  - http-media
  - http-types
  - iproute
  - memory
  - network-uri
  - postgresql-simple
  - QuickCheck
  - relude
  - scientific
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - sqlite-simple
  - text
  - time
  - vault
  - wai

library:
  source-dirs: ./src/

ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

tests:
  stripe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - genvalidity-bytestring
      - genvalidity-sydtest
      - genvalidity-sydtest-aeson
      - http-client
      - http-client-tls
      - stripe
      - sydtest
      - sydtest-discover
      - sydtest-servant
      - sydtest-wai
